-- ============================================================
-- Seed: Standard / Global Risk Assessment Frameworks
-- Run this once against your Supabase project.
-- Requires migration 003 to be applied first (makes org_id nullable).
-- ============================================================

INSERT INTO assessment_frameworks (id, org_id, source_type, name, description, is_active)
VALUES
  (gen_random_uuid(), NULL, 'standard', 'ISO/IEC 27001',
   'International standard for information security management systems (ISMS). Specifies requirements for establishing, implementing, maintaining and improving an ISMS.',
   true),
  (gen_random_uuid(), NULL, 'standard', 'SOC 2 Type II',
   'AICPA framework evaluating a service organisation''s controls relevant to security, availability, processing integrity, confidentiality and privacy over a period of time.',
   true),
  (gen_random_uuid(), NULL, 'standard', 'NIST Cybersecurity Framework (CSF)',
   'NIST voluntary framework of standards, guidelines and practices to manage cybersecurity risk. Core functions: Identify, Protect, Detect, Respond, Recover.',
   true),
  (gen_random_uuid(), NULL, 'standard', 'NIST SP 800-53',
   'Comprehensive catalogue of security and privacy controls for federal information systems and organisations published by NIST.',
   true),
  (gen_random_uuid(), NULL, 'standard', 'PCI DSS v4.0',
   'Payment Card Industry Data Security Standard. Requirements for organisations that handle cardholder data to ensure secure payment card transactions.',
   true),
  (gen_random_uuid(), NULL, 'standard', 'GDPR',
   'EU General Data Protection Regulation. Legal framework governing the collection and processing of personal data of individuals within the European Union.',
   true),
  (gen_random_uuid(), NULL, 'standard', 'HIPAA',
   'Health Insurance Portability and Accountability Act. US regulation establishing national standards for protecting sensitive patient health information.',
   true),
  (gen_random_uuid(), NULL, 'standard', 'ISO 9001:2015',
   'International standard for quality management systems (QMS). Defines requirements for a QMS that consistently provides products and services meeting customer and regulatory requirements.',
   true),
  (gen_random_uuid(), NULL, 'standard', 'ISO 31000:2018',
   'International standard providing principles, a framework and a process for managing risk across any organisation or sector.',
   true),
  (gen_random_uuid(), NULL, 'standard', 'ISO 22301:2019',
   'International standard for business continuity management systems (BCMS). Specifies requirements for planning, implementing and operating continuity processes.',
   true),
  (gen_random_uuid(), NULL, 'standard', 'COBIT 2019',
   'ISACA''s framework for governance and management of enterprise IT. Bridges gaps between control requirements, technical issues and business risks.',
   true),
  (gen_random_uuid(), NULL, 'standard', 'CIS Controls v8',
   'Center for Internet Security Critical Security Controls. Prioritised set of actions that protect organisations from known cyberattack vectors.',
   true),
  (gen_random_uuid(), NULL, 'standard', 'SOX (Sarbanes-Oxley)',
   'US federal law establishing requirements for all US public company boards and management to ensure the accuracy of financial disclosures and internal controls.',
   true),
  (gen_random_uuid(), NULL, 'standard', 'FedRAMP',
   'US government programme providing a standardised approach to security assessment, authorisation and continuous monitoring for cloud products and services.',
   true),
  (gen_random_uuid(), NULL, 'standard', 'CMMC 2.0',
   'Cybersecurity Maturity Model Certification. US Department of Defense framework ensuring defence contractors implement adequate cybersecurity practices.',
   true),
  (gen_random_uuid(), NULL, 'standard', 'DORA (Digital Operational Resilience Act)',
   'EU regulation requiring financial entities to ensure they can withstand, respond to and recover from ICT-related disruptions and threats.',
   true),
  (gen_random_uuid(), NULL, 'standard', 'NIS2 Directive',
   'EU directive on measures for a high common level of cybersecurity across the Union, replacing the original NIS Directive with expanded scope and stricter obligations.',
   true),
  (gen_random_uuid(), NULL, 'standard', 'ISO/IEC 27701:2019',
   'Extension to ISO 27001/27002 providing requirements for a Privacy Information Management System (PIMS). Supports compliance with GDPR and other privacy regulations.',
   true),
  (gen_random_uuid(), NULL, 'standard', 'SWIFT Customer Security Programme (CSP)',
   'SWIFT''s mandatory security baseline framework for financial institutions using the SWIFT network, covering logical and physical access, encryption and monitoring.',
   true),
  (gen_random_uuid(), NULL, 'standard', 'Custom / Ad-hoc',
   'Internal or bespoke assessment framework tailored to your organisation''s specific risk appetite and controls.',
   true)
ON CONFLICT DO NOTHING;
